[package]
name = "rmap"
version = "0.1.0"
authors = ["0x0fbc <10455804+0x0fbc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
